Basic setup for checksumming

diff --git a/spkg b/spkg
--- a/spkg
+++ b/spkg
@@ -102,6 +102,95 @@ function build () {
   rpmbuild -bb "$spec"
 }
 
+function _print_file_checksums () {
+  local file="$1"
+  if ! [ -f "$file" ]; then
+    echo "Usage: $0 path/to/file" >&2
+    return 1
+  fi
+
+  local sumalg sum
+  for sumalg in md5sum sha1sum sha256sum; do
+    sum=`$sumalg "$file" | awk '{ print $1 }'`
+    printf "%-10s %s\n" "$sumalg" "$sum"
+  done
+}
+
+function _verify_sums () {
+  if ! [ -f checksums ]; then
+    echo "No checksums file, cannot verify sums" >&2
+    return
+  fi
+
+  local fsum fname retval=0
+  while read -r fsum fname; do
+    echo "Checking $fname..."
+    if ! [ -f "${SOURCE_DIR}/${fname}" ]; then
+      echo "$fname is missing" >&2
+      retval=$((retval+1))
+      continue
+    fi
+
+    local csum # freshly computed sum
+    csum=`sha256sum "${SOURCE_DIR}/${fname}" | awk '{print $1}'`
+    if [ "$csum" != "$fsum" ]; then
+      echo "Expected $fsum, computed $csum" >&2
+      retval=$((retval+1))
+    fi
+  done < checksums
+  return $retval
+}
+
+function _promptYn () {
+  local resp
+  read -p "$1 [Ynq]: " resp < /dev/tty
+  case resp in
+    n)
+      return 1
+      ;;
+    q)
+      echo "Exiting"
+      exit 0
+      ;;
+    Y|*)
+      return 0
+      ;;
+  esac
+}
+
+function sums () {
+  local spec=`find . -maxdepth 1 -name "*.spec" | head -1`
+  [ -f checksums ] || touch checksums
+  local sname furl fsum fname csum
+  while read -r sname furl; do # spectool
+    echo "$furl =>"
+    # does it exist in the checksums file?
+    local in_checksums=0
+    while read -r fsum fname; do
+      echo $fsum $fname
+      if [ "$fname" = "`basename "$furl"`" ]; then
+        echo "Checksum already exists."
+        in_checksums=1
+      fi
+    done < checksums
+
+    if [ $in_checksums -ne 1 ]; then
+      echo "Is not in the checksums file"
+      local sfile="$SOURCE_DIR"/`basename "$furl"`
+      if [ -f "$sfile" ]; then
+        _print_file_checksums "$sfile"
+        if _promptYn "Add sum to file?"; then
+          csum=`sha256sum "$sfile" | awk '{print $1}'`
+          echo "${csum} `basename $furl`" >> checksums
+        fi
+      else
+        echo "Have not downloaded $furl - cannot compute sum" >&2
+      fi
+    fi
+    echo
+  done < <(spectool -l "$spec" | egrep '(https?|ftp)://')
+}
+
 function process_args () {
   local cmd="$1"
   shift
@@ -116,7 +205,7 @@ function process_args () {
     spkg)
       process_args "$@"
       ;;
-    init|prep|deps|build)
+    init|prep|deps|build|sums)
       $cmd "$@"
       ;;
     *)
